spring.application.name=backend

# database config
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/sketch_arena}
spring.datasource.username=${DB_USERNAME:sketch_arena}
spring.datasource.password=${DB_PASSWORD:sketch_arena_dev}

# run flyway migrations on app startup
spring.flyway.enabled=true

# hibernate compares jpa entites w ones created by flyway
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.jdbc.time_zone=UTC